from _typeshed import Incomplete
from browser import alert as alert, console as console, document as document, html as html, window as window

style_sheet: str

class Menu:
    container: Incomplete
    parent: Incomplete
    default_css: Incomplete
    def __init__(self, container=..., parent: Incomplete | None = ..., default_css: bool = ...) -> None: ...
    def add_item(self, label, callback: Incomplete | None = ..., menu: bool = ...): ...
    def add_link(self, label, href): ...
    def add_menu(self, label): ...
    def hide_menus(self, *args) -> None: ...
    def hide_submenus(self, table) -> None: ...
    def unfold(self, ev) -> None: ...
