from _typeshed import Incomplete
from browser import console as console, window as window

has_local_storage: Incomplete

class _UnProvided: ...

class LocalStorage:
    storage_type: str
    store: Incomplete
    def __init__(self) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __contains__(self, key): ...
    def __iter__(self): ...
    def get(self, key, default: Incomplete | None = ...): ...
    def pop(self, key, default=...): ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...
    def clear(self) -> None: ...
    def __len__(self): ...

storage: Incomplete
