from _typeshed import Incomplete

letters: str

class URL:
    href: Incomplete
    alt: str
    def __init__(self, src) -> None: ...

class CodeBlock:
    lines: Incomplete
    info: Incomplete
    def __init__(self, line) -> None: ...
    def to_html(self): ...

class Marked:
    line: Incomplete
    children: Incomplete
    def __init__(self, line: str = ...) -> None: ...
    def to_html(self): ...

class Script:
    src: Incomplete
    def __init__(self, src) -> None: ...
    def to_html(self): ...

refs: Incomplete
ref_pattern: str

def mark(src): ...
def escape(czone): ...
def s_escape(mo): ...
def unmark(code_zone): ...
def s_unmark(mo): ...
def apply_markdown(src): ...
