from _typeshed import Incomplete

class _UnProvided: ...

class ObjectStorage:
    storage: Incomplete
    def __init__(self, storage) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __contains__(self, key): ...
    def get(self, key, default: Incomplete | None = ...): ...
    def pop(self, key, default=...): ...
    def __iter__(self): ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...
    def clear(self) -> None: ...
    def __len__(self): ...
