from _typeshed import Incomplete
from browser import document as document, html as html

void_elements: Incomplete

def copy(obj): ...

class ElementData:
    __keys__: Incomplete
    def __init__(self, **kw) -> None: ...
    def __setattr__(self, attr, value) -> None: ...
    def to_dict(self): ...
    def clone(self): ...

class TemplateError(Exception): ...

class Template:
    element: Incomplete
    line_mapping: Incomplete
    line_num: int
    indent: int
    python: str
    callbacks: Incomplete
    def __init__(self, element, callbacks=...) -> None: ...
    def add(self, content, elt) -> None: ...
    def add_indent(self, content, elt) -> None: ...
    def write(self, content) -> None: ...
    def parse(self, elt) -> None: ...
    def on(self, element, event, callback) -> None: ...
    def render_attr(self, name, value) -> None: ...
    data: Incomplete
    html: str
    def render(self, **ns) -> None: ...
