from _typeshed import Incomplete
from browser import console as console

def wrap(func, *args): ...

clear_interval: Incomplete
clear_timeout: Incomplete

def set_interval(func, interval, *args): ...
def set_timeout(func, interval, *args): ...
def request_animation_frame(func): ...
def cancel_animation_frame(int_id) -> None: ...
def set_loop_timeout(x) -> None: ...
