core_scripts = [
    'brython_builtins',

    'py_ast_classes',
    'stdlib_paths',
    'unicode_data',
    'version_info',

    'py_tokens',
    'python_tokenizer',
    'py_ast',
    'py2js',
    'loaders',
    'py_utils',
    'py_object',
    'py_type',
    'py_functions',
    'py_io',
    'py_builtin_functions',
    'py_sort',
    'py_exceptions',
    'py_range_slice',
    'py_bytes',
    'py_set',
    'py_import',
    'py_string',
    'py_int',
    'py_long_int',
    'py_float',
    'py_complex',
    'py_dict',
    'py_list',
    'js_objects',
    'py_generator',
    'py_dom',
    'py_pattern_matching',
    'async',
    'py_flags',
    'builtin_modules',
    'ast_to_js',
    'symtable',

    'action_helpers',
    'string_parser',
    'number_parser',
    'python_parser',
    'pegen',
    'gen_parse',
    'brython_ready'

]
