__BRYTHON__.implementation = [3, 0, 2, 'alpha', 0]
__BRYTHON__.__MAGIC__ = "3.0.2"
__BRYTHON__.version_info = [3, 3, 0, 'alpha', 0]
__BRYTHON__.builtin_module_names = ["posix","__random",
    "_ajax",
    "_browser",
    "_html",
    "_io",
    "_jsre",
    "_multiprocessing",
    "_os",
    "_posixsubprocess",
    "_svg",
    "_sys",
    "_timer",
    "_websocket",
    "builtins",
    "dis",
    "hashlib",
    "javascript",
    "json",
    "math",
    "modulefinder",
    "time",
    "_codecs",
    "_collections",
    "_csv",
    "_dummy_thread",
    "_functools",
    "_imp",
    "_io",
    "_markupbase",
    "_random",
    "_socket",
    "_sre",
    "_string",
    "_struct",
    "_sysconfigdata",
    "_testcapi",
    "_thread",
    "_warnings",
    "_weakref"]
